# Generated by Django 3.2 on 2021-04-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0002_adoptrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Longitude', models.FloatField(help_text='Longitude of the sight', max_length=30)),
                ('Latitude', models.FloatField(help_text='Latitude of the sight', max_length=30)),
                ('Unique_Squirrel_ID', models.CharField(help_text='The unique ID of the squirrel', max_length=30)),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', help_text='AM or PM', max_length=2)),
                ('Date', models.DateField(blank=True, default=None, help_text='Date sighted. The format is in mmddyyyy', null=True)),
                ('Age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), (None, ''), ('?', '?')], default='', help_text='Adult or Juvenile', max_length=30)),
                ('Primary_Fur_Color', models.CharField(blank=True, choices=[('Black', 'Black'), ('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), (None, '')], help_text='Fur color', max_length=16)),
                ('Location', models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground'), (None, '')], help_text='Location', max_length=100)),
                ('Specific_Location', models.CharField(blank=True, help_text='Specific location', max_length=100)),
                ('Running', models.NullBooleanField(help_text='Running')),
                ('Chasing', models.NullBooleanField(help_text='Chasing')),
                ('Climbing', models.NullBooleanField(help_text='Climbing')),
                ('Eating', models.NullBooleanField(help_text='Eating')),
                ('Foraging', models.NullBooleanField(help_text='Foraging')),
                ('Other_Activities', models.CharField(blank=True, help_text='Other Activities', max_length=1000, null=True)),
                ('Kuks', models.NullBooleanField(help_text='Kuks')),
                ('Quaas', models.NullBooleanField(help_text='Quaas')),
                ('Moans', models.NullBooleanField(help_text='Moans')),
                ('Tail_flags', models.NullBooleanField(help_text='Tail flags')),
                ('Tail_twitches', models.NullBooleanField(help_text='Tail twitches')),
                ('Approaches', models.NullBooleanField(help_text='Approaches')),
                ('Indifferent', models.NullBooleanField(help_text='Indifferent')),
                ('Runs_from', models.NullBooleanField(help_text='Runs_From')),
            ],
        ),
        migrations.DeleteModel(
            name='AdoptRequest',
        ),
        migrations.DeleteModel(
            name='Sight',
        ),
    ]
