# Generated by Django 3.2 on 2021-04-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0003_auto_20210413_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='Longitude',
            field=models.FloatField(help_text='Longitude of the sight', max_length=30, null=True),
        ),
    ]
