# Generated by Django 3.2 on 2021-04-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0004_alter_sighting_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='Longitude',
            field=models.FloatField(blank=True, help_text='Longitude of the sight', max_length=30, null=True),
        ),
    ]
