# Generated by Django 3.0.7 on 2021-04-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0005_alter_sighting_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
